name = "pizzapilot"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/public"

[env.production]
vars = { NODE_ENV = "production" }

[env.production.secrets]
DATABASE_URL = ""

[env.preview]
vars = { NODE_ENV = "preview" }

[env.preview.secrets]
DATABASE_URL = ""

